---
title: "Lecture 9"
subtitle: " "
author: "JMG"
institute: "MATH 204"
output:
  xaringan::moon_reader:
    css: [rladies, rladies-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(openintro)
library(tidyverse)
library(ggformula)
library(patchwork)
library(latex2exp)
library(kableExtra)
```

# Further Inference

- Now that we have introduced the foundations of statistical inference, we study in detail some of the most common basic inference for 

--

  - a single proportion (6.1)
  
--

  - a difference of two proportions (6.2)
  
--

  - one-sample means (7.1)
  
--

  - paired data (7.3)
  
--

  - a difference of two means (7.3)
  
--

- After we discuss these topics along with power calculations and simple ordinary least squares regress (7.4 and Chapter 8), we will return to discuss goodness (6.3) of fit and testing for independence (6.4).


---

# Learning Objectives



---

# Central Limit Theorems

- Recall our CLT for sample proportion:

> When observations are independent and sample size is sufficiently large, then then the sampling distribution for the sample proportion $\hat{p}$ is approximately normal with mean $\mu_{\hat{p}}=p$ and standard error $SE_{\hat{p}}=\sqrt{\frac{p(1-p)}{n}}$.

--

- We also have a CLT for the sample mean:

> When we collect samples of sufficiently large size $n$ from a population with mean $\mu$ and standard deviation $\sigma$, then the sampling distribution for the sample mean $\bar{x}$ is approximately normal with mean $\mu$ and standard error $SE = \frac{\sigma}{\sqrt{n}}$. 

--

- Later we will return to discuss precisely what we mean by "samples of sufficiently large size."

--

- We use sampling distributions for obtaining confidence intervals and conducting hypothesis tests. 


---

# CI for a Proportion


---

# Hypothesis Test for a Proportion



---

# R Commands for Proportion Test


---

# Sampling Distribution for Difference of Proportions

---

# Hypothesis Test for Difference of Proportions


---

# R Commands for Difference of Proportion Test


---

# Practical Check for Normality 


---

# t-distribution


---

# One-Sample t CI


---

# One-Sample t-test


---

# R Command for One-Sample t-test


---

# Paired Data

